require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7

Metrics/BlockLength:
  Max: 100

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/InstanceVariable:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
